#!/usr/bin/env node

const fs = require("fs");
const os = require("os");
require("dotenv").config();
const util = require("util");
const fetch = require("node-fetch");
const fileType = require("file-type");
const streamPipeline = util.promisify(require("stream").pipeline);

let key = "AIzaSyDxflsfyd2gloxgWJ-GFtPM46tz-TtOXh8";

const baseUrl = "https://www.onivim.io";

/*
 * Validate license key
 */
async function isLicenseKeyValid(licenseKey) {
  // {{{
  let response = await fetch(
    `${baseUrl}/api/isLicenseKeyValid?licenseKey=${licenseKey}`
  );
  return await response.json();
} // }}}

/*
 * Handle vendor authentication
 */
async function authLicenseKey(licenseKey) {
  // {{{
  if (isLicenseKeyValid()) {
    let response = await fetch(
      `${baseUrl}/auth/licenseKey?licenseKey=${licenseKey}`
    );
    return await response.json();
  }
} // }}}

/*
 * Handle Google Identity Toolkit authentication
 */
async function verifyCustomToken(token) {
  // {{{
  let response = await fetch(
    `https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyCustomToken?key=${key}`,
    {
      body: `{"token":"${token}","returnSecureToken":true}`,
      method: "POST",
    }
  );
  return await response.json();
} // }}}

/*
 * Get Google Identity Toolkit account information
 */
async function getAccountInfo(idToken) {
  // {{{
  let response = await fetch(
    `https://www.googleapis.com/identitytoolkit/v3/relyingparty/getAccountInfo?key=${key}`,
    {
      body: `{"idToken":"${idToken}"}`,
      method: "POST",
    }
  );

  return response.json();
} // }}}

/*
 * Get current release notes or latest commit id (HEAD).
 */
async function getReleaseNotes() {
  // {{{
  const response = await fetch("https://www.onivim.io/api/getReleaseNotes", {
    referrer: "https://www.onivim.io/early-access-portal",
  });
  return response.json();
} // }}}

/*
 * Get information about currently available downloads.
 * Requires authentication.
 */
async function getDownloads(token, channel) {
  // {{{
  let response = await fetch(
    `${baseUrl}/api/getDownloads?channel=${channel}&token=${token}`
  );
  return response.json();
} // }}}

/*
 * Authenticate or fail.
 */
async function auth() {
  // {{{
  let licenseKey = process.env.ONIVIM2_LICENSE_KEY;
  let { token } = await authLicenseKey(licenseKey);
  let { idToken } = await verifyCustomToken(token);
  if (!idToken) {
    console.error(`Authenticating failed`, licenseKey, token, idToken);
  }
  return idToken;
} // }}}

/*
 * Download Onivim.
 */
async function download({ platform, channel, token }) {
  // {{{
  const response = await fetch(
    `https://v2.onivim.io/downloads/Onivim2-${platform}.tar.gz?channel=${channel}&token=${token}`
  );

  if (response.ok) {
    return streamPipeline(
      response.body,
      fs.createWriteStream(`Onivim2-${platform}.tar.gz`)
    );
  }

  const buffer = await response.buffer();
  const type = fileType.fromBuffer(buffer);

  console.log(type);
} // }}}

/*
 * Parse args and do the things
 */
function main() {
  argv = require("yargs")
    .command(
      "license",
      "Validate license key",
      () => {},
      async () => {
        (await isLicenseKeyValid(process.env.LICENSE_KEY))
          ? process.exit(0)
          : process.exit(1);
      }
    )
    .command(
      "cur",
      "Get current version",
      () => {},
      async ({ channel }) => {
        let idToken = await auth();
        let response = await getDownloads(idToken, channel);
        console.log(response);
      }
    )
    .command(
      "account",
      "Get user account info",
      () => {},
      async ({ channel }) => {
        let idToken = await auth();
        let { users } = await getAccountInfo(idToken, channel);
        console.log(users[0]);
      }
    )
    .command(
      "head",
      "Get latest commit",
      () => {},
      async () => {
        let { commitId } = await getReleaseNotes();
        console.log(commitId);
      }
    )
    .command("download", "Download Onivim", async (argv) => {
      await download({
        platform: argv.platform,
        channel: argv.channel,
        token: await auth(),
      });
    })
    .option("channel", {
      alias: "c",
      type: "string",
      description: "Select channel",
      default: "stable",
    })
    .option("platform", {
      alias: "p",
      type: "string",
      description: "Select platform",
      default: os.platform(),
    })
    .option("verbose", {
      alias: "v",
      type: "boolean",
      description: "Verbose output",
    }).argv;
}

main();
